# permissions for end users to edit mutilcninetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutilcninetwork-editor-role
rules:
- apiGroups:
  - net.linshanyu.com
  resources:
  - mutilcninetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.linshanyu.com
  resources:
  - mutilcninetworks/status
  verbs:
  - get
