# permissions for end users to view mutilcninetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutilcninetwork-viewer-role
rules:
- apiGroups:
  - net.linshanyu.com
  resources:
  - mutilcninetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.linshanyu.com
  resources:
  - mutilcninetworks/status
  verbs:
  - get
